Feat/add fira sim basics
Equipe-Botcem/Equipe-Botcem.github.io pull request #15
Opened 2023-02-22 06:20 UTC by AlMaciel06

2023-02-22 18:27 UTC, LuisHenri requested changes
- Tirar espaço do começo da linha onde não precisa
- Tirar os cifrões

---

Dica:
- Nos comentários onde eu fiz sugestões, você pode aplicar elas em "batch" para que fiquem dentro do mesmo commit:
![image](https://user-images.githubusercontent.com/44511825/220722833-622ec24c-0f16-4aca-8a7a-553d5089e2d7.png)

2023-02-22 18:27 UTC, LuisHenri commented on docs/VSSS/Tutorials/FIRASim_Basic.md
> +O repositório contendo o código fonte e os manuais de instalação estão contidos no site: [https://github.com/robocin/FIRASim](https://github.com/robocin/FIRASim)
```suggestion
O repositório contendo o código fonte e os manuais de instalação estão contidos no [repositório original do FIRASim](https://github.com/robocin/FIRASim).
```

2023-02-22 18:27 UTC, LuisHenri commented on docs/VSSS/Tutorials/FIRASim_Basic.md
> +O Software foi desenvolvido no Ubuntu 18.04, escrito em C++ e feito pela equipe de competição RoboCin.
```suggestion
O Software foi desenvolvido no **Ubuntu 18.04**, escrito em C++ e feito pela equipe de competição RoboCin.
```

2023-02-22 18:27 UTC, LuisHenri commented on docs/VSSS/Tutorials/FIRASim_Basic.md
> +
Acho que qualquer computador hoje tem isso
```suggestion
```

2023-02-22 18:27 UTC, LuisHenri commented on docs/VSSS/Tutorials/FIRASim_Basic.md
> + ## Dependências
Tem um espaço na frente das Hashtags

```suggestion
## Dependências 
```

2023-02-22 18:27 UTC, LuisHenri commented on docs/VSSS/Tutorials/FIRASim_Basic.md
> + FIRASim depends on:
```suggestion
O FIRASim depende de: 
```

2023-02-22 18:27 UTC, LuisHenri commented on docs/VSSS/Tutorials/FIRASim_Basic.md
> +- C++
```suggestion
- [C++](https://en.cppreference.com/w/)
```

2023-02-22 18:27 UTC, LuisHenri commented on docs/VSSS/Tutorials/FIRASim_Basic.md
> + $ sudo apt-get install git build-essential cmake qt5-default libqt5opengl5-dev libgl1-mesa-dev libglu1-mesa-dev libprotobuf-dev protobuf-compiler libode-dev libboost-dev
Não precisa do cifrão e do espaço na frente.
(Pode tirar pras ocorrências seguintes também)

```suggestion
Primeiramente, abra um terminal e instale as dependências já citadas:

```bash 
sudo apt-get install git build-essential cmake qt5-default libqt5opengl5-dev libgl1-mesa-dev libglu1-mesa-dev libprotobuf-dev protobuf-compiler libode-dev libboost-dev 
```

2023-02-22 18:27 UTC, LuisHenri commented on docs/VSSS/Tutorials/FIRASim_Basic.md
> + Compile e instale VartTypes de seu source, usando git:
```suggestion
 Compile e instale o VarTypes a partir do seu código fonte:
```

2023-02-22 18:27 UTC, LuisHenri commented on docs/VSSS/Tutorials/FIRASim_Basic.md
> + Crie um diretório dentro da pasta do projeto chamado "build" (Ignorado pelo gitignore) e entre nela:
```suggestion
 Crie uma pasta dentro do diretório chamada `build` e entre nela:
```

2023-02-22 18:27 UTC, LuisHenri commented on docs/VSSS/Tutorials/FIRASim_Basic.md
> + $ make
```suggestion
Execute o Cmake de dentro de `build` para gerar o makefile e compile o programa:
  
```bash 
cmake ..
make 
```

2023-02-22 18:27 UTC, LuisHenri commented on docs/VSSS/Tutorials/FIRASim_Basic.md
> + O binário(Executável) é copiado para a pasta '../bin' depois de ter compilado o código.
```suggestion
O binário (executável) é gerado dentro da pasta `FIRASim/bin` após compilação do código.
```

2023-02-22 18:27 UTC, LuisHenri commented on docs/VSSS/Tutorials/FIRASim_Basic.md
> + Para rodar o programa, execute-o como qualquer outro programa em C('./FIRASim' dentro da pasta do binário), ou, mais recomendado, dentro da pasta 'build' inserir no terminal './../bin/FIRASim'.
```suggestion
Para rodar o programa, execute-o a partir da raiz do projeto: `./bin/FIRASim`
```

2023-02-22 18:27 UTC, LuisHenri commented on docs/VSSS/Tutorials/FIRASim_Basic.md
> + - "-xlr8": para usar uma função mais rápida e menos precisa da ODE
```suggestion
- `-H`: para rodar o software sem a interface gráfica;
- `-atkfault`: para ativar a detecção de dois robôs adversários dentro da área;
- `-xlr8`: para usar uma função mais rápida e menos precisa da ODE.
```

2023-02-22 22:52 UTC, longovinicius requested changes

2023-03-12 03:22 UTC, LuisHenri approved these changes

2023-03-16 12:50 UTC, longovinicius approved these changes
Tudo certo!!!

2023-03-16 12:57 UTC, merged