Update info Microcontrolador.md
Equipe-Botcem/Equipe-Botcem.github.io pull request #27
Opened 2023-07-30 23:34 UTC by andrebarbadoUFSC

add informaçoes

2023-07-31 01:43 UTC, LuisHenri requested changes
❤️

2023-07-31 01:43 UTC, LuisHenri commented on docs/Componentes-e-Ferramentas/Microcontrolador.md
> +Os microcontroladores são pequenos computadores em um único chip. Eles contêm processadores, memória e interfaces de entrada/saída (I/O). Estes são usados em muitos produtos eletrônicos, pois são peq
Eu sei a diferença, mas não sei se ficou muito clara a diferença entre os Chips Microcontroladores e a plaquinha em si.
No Arduíno essa diferença é um pouco mais clara porque são nomes diferentes, mas nos ESPs a gente chama tanto a plaquinha final quanto o chip de "ESP"

2023-07-31 01:43 UTC, LuisHenri commented on docs/Componentes-e-Ferramentas/Microcontrolador.md
> +Os microcontroladores são pequenos computadores em um único chip. Eles contêm processadores, memória e interfaces de entrada/saída (I/O). Estes são usados em muitos produtos eletrônicos, pois são peq
Eu também juntaria as duas primeiras frases com um "..., que contêm..."

2023-07-31 01:45 UTC, LuisHenri commented
Outro rolê de a gente já se forçar a usar PR desde já é criar exemplos prós que vierem depois (até mesmo os gerentes). Eles podem simplesmente visualizar como foram feitos os PRs no passado

2023-07-31 11:08 UTC, LuisHenri commented on docs/Componentes-e-Ferramentas/Microcontrolador.md
> +Os microcontroladores são pequenos computadores em um único chip. Eles contêm processadores, memória e interfaces de entrada/saída (I/O). Estes são usados em muitos produtos eletrônicos, pois são peq
@andrebarbadoUFSC Você marcou como "Resolvido", mas não tem nenhum commit novo aqui. Será que esqueceu de dar `git push`?

2023-07-31 11:09 UTC, LuisHenri commented
@andrebarbadoUFSC Depois de realizar as alterações, é interessante re-requisitar as revisões pra que os revisores sejam notificados:
![image](https://github.com/Equipe-Botcem/Equipe-Botcem.github.io/assets/44511825/b42db947-a4ba-4167-960b-95b30cdccfab)

2023-11-05 21:52 UTC, andrebarbadoUFSC commented on docs/Componentes-e-Ferramentas/Microcontrolador.md
> +Os microcontroladores são pequenos computadores em um único chip. Eles contêm processadores, memória e interfaces de entrada/saída (I/O). Estes são usados em muitos produtos eletrônicos, pois são peq
eu fiz bem por cima, quero que o pessoal melhore, não vou dar o peixe kkk por isso nao alterei

2023-11-05 22:33 UTC, LuisHenri commented on docs/Componentes-e-Ferramentas/Microcontrolador.md
> +Os microcontroladores são pequenos computadores em um único chip. Eles contêm processadores, memória e interfaces de entrada/saída (I/O). Estes são usados em muitos produtos eletrônicos, pois são peq
As desculpas do cara, ae

2023-11-05 22:34 UTC, LuisHenri approved these changes

2023-11-05 22:57 UTC, merged