Update index.md
Equipe-Botcem/Equipe-Botcem.github.io pull request #30
Opened 2023-09-12 23:09 UTC by arthurhn

atualização no regulamento, frefletir políticas da equipe em 2023

2023-09-12 23:17 UTC, LuisHenri requested changes
Nem uma seçãozinha sobre machismo e homofobia? :(

2023-09-12 23:17 UTC, LuisHenri commented on docs/Regulamento/index.md
>  **METODOLOGIA SCRUM**
Talvez colocar um link pra própria página sobre SCRUM que já tem?
`/docs/Guidelines/Scrum.md`

2023-09-12 23:17 UTC, LuisHenri commented on docs/Regulamento/index.md
>  **Art.4º** - Caso seja necessário, mediante aprovação da capitania e  de ⅔ dos gerentes de célula, um membro pode ser colocado em processo re-avaliativo.
Tem um espaço a mais em `da capitania e  de"

2023-09-13 00:00 UTC, arthurhn commented on docs/Regulamento/index.md
>  **Art.4º** - Caso seja necessário, mediante aprovação da capitania e  de ⅔ dos gerentes de célula, um membro pode ser colocado em processo re-avaliativo.
Acho que não altera nada em markdown

2023-09-13 00:00 UTC, LuisHenri approved these changes

2023-09-13 00:00 UTC, arthurhn commented
> Nem uma seçãozinha sobre machismo e homofobia? :(

Adicionado

2023-09-13 00:03 UTC, arthurhn commented on docs/Regulamento/index.md
>  **METODOLOGIA SCRUM**
Adicionado ao subtítulo de metodologia scrum

2023-09-13 00:21 UTC, merged